<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Error Handling | Javascript OOP</title>
  </head>
  <body>
    <h1>Error | Javascript OOP</h1>
    <script>
      // untuk error handling kita dapat menggunakan try dan catch agar kode tidak berhenti
      class MathUtil {
        static sum(...numbers) {
          if (numbers.length == 0) {
            throw new Error('Nilai pada parameter tidak boleh 0');
          }
          let total = 0;
          for (const number of numbers) {
            total += number;
          }
          return total;
        }
      }
      // aktifkan code dibawah ini untuk melihat perbedaan

      // const number = new MathUtil.sum();
      // console.log(number);

      // contoh menggunakan try catch matikan kode diatas untuk melihat perbedaan
      try {
        console.info(MathUtil.sum());
      } catch (error) {
        console.error(`Terjadi Error: ${error.message}`);
      } finally {
        console.info('Program Selesai');
      }
      console.info('Agung');

      console.info('Akan Tetap lanjut');

      // jika tidak ingin menggunakan catch kita bisa langsung menggunakan finally
      class Counter {
        #counter = 1;
        next() {
          try {
            return this.#counter;
          } finally {
            this.#counter++;
          }
        }
      }

      const count = new Counter();
      console.info(count.next());
      console.info(count.next());
      console.info(count.next());
      console.info(count.next());
      console.info(count.next());
      console.info(count.next());
    </script>
  </body>
</html>
